name: Build and Deploy to Cloud Run with Workload Identity Federation

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: meta-sensor-380711
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authenticate using Workload Identity Federation'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_pool: 'projects/326614876881/locations/global/workloadIdentityPools/my-pool'
          role: 'roles/iam.workloadIdentityUser'
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: 'Build and Deploy'
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image
          gcloud run deploy csv-to-parquet \
            --image gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --allow-unauthenticated

      - name: 'Execute Cloud Run Job'
        uses: google-github-actions/https://github.com/Supriya-2001/cloud-run-job@v1
        with:
          service-name: 'csv-to-parquet'
          project-id: ${{ env.PROJECT_ID }}
          location: ${{ env.REGION }}
          json-payload: '{"input_bucket": "csvfile-bucket", "output_bucket": "bucket-to-store-parquet-in-gcp"}'
          service-account-email: ${{ secrets.GCLOUD_SA_EMAIL}}
          credentials: ${{ secrets.GCLOUD_SA_KEY }}
