name: Build and Deploy to Cloud Run with Workload Identity Federation

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: meta-sensor-380711
  REGION: us-central1
  JOB_NAME: csv-to-parquet-image-job

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./path/to/Dockerfile/directory
          dockerfile: Dockerfile
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image-job


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authenticate using Workload Identity Federation'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_pool: 'projects/326614876881/locations/global/workloadIdentityPools/my-pool'
          role: 'roles/iam.workloadIdentityUser'
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: 'Build and Deploy'
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/csv-to-parquet-image

      - name: 'Execute Cloud Run Job'
        run: |
          gcloud beta run jobs create ${{ env.JOB_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --service ${{ env.SERVICE_NAME }} \
