name: Build and Deploy to Cloud Run with Workload Identity Federation

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: meta-sensor-380711
  REGION: us-central1
  JOB_NAME: csv-to-parquet-image-job

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authenticate using Workload Identity Federation'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_pool: 'projects/326614876881/locations/global/workloadIdentityPools/my-pool'
          role: 'roles/iam.workloadIdentityUser'
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: 'create cloud run job'
        run: |
           gcloud run jobs create secondjob123456 \
           --image gcr.io/meta-sensor-380711/csv-to-parquet-image \
           --region ${{ env.REGION }} \
           --max-retries 2 \

      - name: 'Execute Cloud Run Job'
        run: |
          gcloud run jobs execute secondjob123456 \
          --region=us-central1 \
          --service=csv-to-parquet \
          --platform=managed \
