name: Build and Deploy to Cloud Run with Workload Identity Federation

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: meta-sensor-380711
  REGION: us-central1
  JOB_NAME: git-cloudjob

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authenticate using Workload Identity Federation'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_pool: 'projects/326614876881/locations/global/workloadIdentityPools/my-pool'
          role: 'roles/iam.workloadIdentityUser'
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: 'create cloud run job'
        run: |
          gcloud run jobs create git-cloudjob \
          --image=gcr.io/meta-sensor-380711/cloudjob-updated\
          --region=us-central1 \
          --tasks=1 \
          --task-timeout=300 \
          --set-env-vars=BUCKET=csvfile-bucket \
          --set-env-vars=PROCESSOR_ID=2271838ac1cc \
        
      - name: 'Execute Cloud Run Job'
        run: |
          gcloud run jobs execute git-cloudjob \
          --region=us-central1 \
  
